---
- name: Converge
  hosts: all

  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
      changed_when: no
      when: ansible_pkg_mgr == 'apt'

    - name: Install gnupg2 (apt)
      become: yes
      ansible.builtin.apt:
        name: gnupg2
        state: present
      when: ansible_pkg_mgr == 'apt'

    - name: Install extension cli dependencies (apt)
      become: yes
      ansible.builtin.apt:
        name: libx11-xcb1
        state: present
      when: ansible_pkg_mgr == 'apt'

  roles:
    - role: ansible-role-visual-studio-code
      visual_studio_code_gpgcheck: no

  post_tasks:
    - name: Install which
      ansible.builtin.package:
        name: which
        state: present
      when: ansible_pkg_mgr in ('yum', 'dnf', 'zypper')
