---
dependency:
  name: galaxy

driver:
  name: docker

role_name_check: 2

platforms:
  - name: ansible-role-visual-studio-code-ubuntu-min-trusted-true
    image: ubuntu:20.04

provisioner:
  name: ansible
  playbooks:
    converge: ./converge.yml
  inventory:
    host_vars:
      instance:
        ansible_user: ansible

verifier:
  name: testinfra
  directory: ./tests
