---
dependency:
  name: galaxy

driver:
  name: docker

lint: |
  set -e
  yamllint .
  ansible-lint
  flake8

platforms:
  - name: ansible-role-visual-studio-code-ubuntu-signed-by
    image: ubuntu:22.04

provisioner:
  name: ansible
  playbooks:
    converge: ./converge.yml
  inventory:
    host_vars:
      instance:
        ansible_user: ansible

verifier:
  name: testinfra
  directory: ./tests
