---
dependency:
  name: galaxy

driver:
  name: docker

lint:
  name: yamllint

platforms:
  - name: ansible-role-visual-studio-code-fedora
    image: fedora:31
    dockerfile: ../centos/Dockerfile.j2

provisioner:
  name: ansible
  playbooks:
    converge: ../code-only/playbook.yml
  lint:
    name: ansible-lint
  inventory:
    host_vars:
      instance:
        ansible_user: ansible

scenario:
  name: fedora

verifier:
  name: testinfra
  directory: ../code-only/tests
  lint:
    name: flake8
