---
- name: assert supported distribution
  assert:
    that:
      - "ansible_pkg_mgr in ('apt', 'yum', 'dnf', 'zypper', 'homebrew')"

- name: 'install ({{ ansible_pkg_mgr }})'
  include_tasks: 'install-{{ ansible_pkg_mgr }}.yml'
