---
- name: load version vars
  with_first_found:
    - "../vars/versions/{{ visual_studio_code_version }}.yml"
    - ../vars/versions/default.yml
  include_vars: "{{ item }}"

- name: assert version vars
  assert:
    that:
      - "visual_studio_code_redis_sha256sum not in (None, '')"
      - "visual_studio_code_redis_url not in (None, '')"

- name: create download directory
  file:
    state: directory
    mode: 'u=rwx,go=rx'
    dest: "{{ visual_studio_code_download_dir }}"

- name: ensure ca-certificates installed
  become: yes
  apt:
    name: ca-certificates
    state: present

- name: download Visual Studio Code
  get_url:
    url: "{{ visual_studio_code_redis_url }}"
    dest: "{{ visual_studio_code_download_dir }}/{{ visual_studio_code_redis_filename }}"
    sha256sum: "{{ visual_studio_code_redis_sha256sum }}"
    force: no
    use_proxy: yes
    validate_certs: yes
    mode: 'u=rw,go=r'

- name: install Visual Studio Code
  become: yes
  apt:
    deb: "{{ visual_studio_code_download_dir }}/{{ visual_studio_code_redis_filename }}"
