---
dependency:
  name: galaxy

driver:
  name: docker

lint: |
  set -e
  yamllint .
  ansible-lint
  flake8

platforms:
  - name: ansible-role-visual-studio-code-centos
    image: centos:7

provisioner:
  name: ansible
  playbooks:
    converge: ../code-only/converge.yml
  inventory:
    host_vars:
      instance:
        ansible_user: ansible

verifier:
  name: testinfra
  directory: ../code-only/tests
