---
dependency:
  name: galaxy

driver:
  name: docker

lint:
  name: yamllint

platforms:
  - name: ansible-role-visual-studio-code-ubuntu-min
    image: ubuntu:16.04
    dockerfile: ../default/Dockerfile.j2

provisioner:
  name: ansible
  playbooks:
    converge: ../default/playbook.yml
  lint:
    name: ansible-lint
  inventory:
    host_vars:
      instance:
        ansible_user: ansible

scenario:
  name: ubuntu-min

verifier:
  name: testinfra
  directory: ../default/tests
  lint:
    name: flake8
