---
dependency:
  name: galaxy

driver:
  name: docker

lint: |
  set -e
  yamllint .
  ansible-lint
  flake8

platforms:
  - name: ansible-role-visual-studio-code-ubuntu-max
    image: ubuntu:18.04

provisioner:
  name: ansible
  inventory:
    host_vars:
      instance:
        ansible_user: ansible

verifier:
  name: testinfra
